version: '3.8'

services:
  backend:
    build: ./app
    ports:
      - "3000:3000"
    env_file:
      - app/.env
    depends_on:
      - mongo

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    env_file:
      - frontend/.env
    depends_on:
      - backend

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

volumes:
  mongo-data:
